-- 回滚HXWKDEFINITIONS表复合主键的PostgreSQL脚本
-- 回滚时间：2025-02-21 05:00:00

-- 注意：此脚本会删除VERSION列，请确保没有重要数据需要保留

-- 1. 删除检查约束
ALTER TABLE "HXWKDEFINITIONS" DROP CONSTRAINT IF EXISTS "CK_HXWKDEFINITIONS_VERSION_POSITIVE";

-- 2. 删除索引
DROP INDEX IF EXISTS "IX_HXWKDEFINITIONS_VERSION";
DROP INDEX IF EXISTS "IX_HXWKDEFINITIONS_ID";
DROP INDEX IF EXISTS "IX_HXWKDEFINITIONS_ID_VERSION";

-- 3. 删除外键约束
ALTER TABLE "HXDEFINITION_CANDIDATES" DROP CONSTRAINT IF EXISTS "Pk_WkDef_Candidate";
ALTER TABLE "HXWKNODES" DROP CONSTRAINT IF EXISTS "Pk_WkDef_WkNode";
ALTER TABLE "HXWKINSTANCES" DROP CONSTRAINT IF EXISTS "Pk_Instance_Definition";
ALTER TABLE "HXNODE_CANDIDATES" DROP CONSTRAINT IF EXISTS "Pk_WkNode_Candidate";
ALTER TABLE "HX_NODES_APPLICATION_FORMS" DROP CONSTRAINT IF EXISTS "NODE_FKEY";

-- 4. 删除复合主键约束
ALTER TABLE "HXWKDEFINITIONS" DROP CONSTRAINT IF EXISTS "PK_WKDEFINITION";

-- 5. 删除VERSION列
ALTER TABLE "HXWKDEFINITIONS" DROP COLUMN IF EXISTS "VERSION";
ALTER TABLE "HXDEFINITION_CANDIDATES" DROP COLUMN IF EXISTS "VERSION";
ALTER TABLE "HXNODE_CANDIDATES" DROP COLUMN IF EXISTS "VERSION";
ALTER TABLE "HXPOINTER_CANDIDATES" DROP COLUMN IF EXISTS "VERSION";
ALTER TABLE "HXWKNODES" DROP COLUMN IF EXISTS "VERSION";
ALTER TABLE "HXWKINSTANCES" DROP COLUMN IF EXISTS "VERSION";
ALTER TABLE "HX_NODES_APPLICATION_FORMS" DROP COLUMN IF EXISTS "VERSION";

-- 6. 重新创建单主键
ALTER TABLE "HXWKDEFINITIONS" ADD CONSTRAINT "PK_WKDEFINITION" PRIMARY KEY ("ID");

-- 7. 重新创建外键约束（单字段）
ALTER TABLE "HXDEFINITION_CANDIDATES" ADD CONSTRAINT "Pk_WkDef_Candidate" 
    FOREIGN KEY ("NODEID") 
    REFERENCES "HXWKDEFINITIONS" ("ID");

ALTER TABLE "HXWKNODES" ADD CONSTRAINT "Pk_WkDef_WkNode" 
    FOREIGN KEY ("WKDIFINITIONID") 
    REFERENCES "HXWKDEFINITIONS" ("ID");

ALTER TABLE "HXWKINSTANCES" ADD CONSTRAINT "Pk_Instance_Definition" 
    FOREIGN KEY ("WKDIFINITIONID") 
    REFERENCES "HXWKDEFINITIONS" ("ID");

ALTER TABLE "HXNODE_CANDIDATES" ADD CONSTRAINT "Pk_WkNode_Candidate" 
    FOREIGN KEY ("NODEID") 
    REFERENCES "HXWKNODES" ("ID");

ALTER TABLE "HX_NODES_APPLICATION_FORMS" ADD CONSTRAINT "NODE_FKEY" 
    FOREIGN KEY ("NODE_ID") 
    REFERENCES "HXWKNODES" ("ID");

-- 8. 验证回滚结果
DO $$
BEGIN
    -- 检查主键是否存在
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE table_name = 'HXWKDEFINITIONS' 
        AND constraint_name = 'PK_WKDEFINITION'
        AND constraint_type = 'PRIMARY KEY'
    ) THEN
        RAISE EXCEPTION '单主键创建失败';
    END IF;
    
    -- 检查VERSION列是否已删除
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'HXWKDEFINITIONS' 
        AND column_name = 'VERSION'
    ) THEN
        RAISE EXCEPTION 'HXWKDEFINITIONS表VERSION列删除失败';
    END IF;
    
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'HXDEFINITION_CANDIDATES' 
        AND column_name = 'VERSION'
    ) THEN
        RAISE EXCEPTION 'HXDEFINITION_CANDIDATES表VERSION列删除失败';
    END IF;
    
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'HXNODE_CANDIDATES' 
        AND column_name = 'VERSION'
    ) THEN
        RAISE EXCEPTION 'HXNODE_CANDIDATES表VERSION列删除失败';
    END IF;
    
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'HXPOINTER_CANDIDATES' 
        AND column_name = 'VERSION'
    ) THEN
        RAISE EXCEPTION 'HXPOINTER_CANDIDATES表VERSION列删除失败';
    END IF;
    
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'HXWKNODES' 
        AND column_name = 'VERSION'
    ) THEN
        RAISE EXCEPTION 'HXWKNODES表VERSION列删除失败';
    END IF;
    
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'HXWKINSTANCES' 
        AND column_name = 'VERSION'
    ) THEN
        RAISE EXCEPTION 'HXWKINSTANCES表VERSION列删除失败';
    END IF;
    
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'HX_NODES_APPLICATION_FORMS' 
        AND column_name = 'VERSION'
    ) THEN
        RAISE EXCEPTION 'HX_NODES_APPLICATION_FORMS表VERSION列删除失败';
    END IF;
    
    RAISE NOTICE 'HXWKDEFINITIONS表回滚到单主键完成';
END $$; 