-- 添加 VERSION 字段到需要版本控制的表
-- 注意：ExePointerCandidate 不需要版本控制，所以不添加 VERSION 字段

-- 为 HXWKDEFINITIONS 添加 VERSION 字段
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'HXWKDEFINITIONS' AND column_name = 'VERSION') THEN
        ALTER TABLE "HXWKDEFINITIONS" ADD COLUMN "VERSION" INTEGER NOT NULL DEFAULT 1;
        RAISE NOTICE '已为 HXWKDEFINITIONS 添加 VERSION 字段';
    ELSE
        RAISE NOTICE 'HXWKDEFINITIONS 的 VERSION 字段已存在';
    END IF;
END $$;

-- 为 HXDEFINITION_CANDIDATES 添加 VERSION 字段
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'HXDEFINITION_CANDIDATES' AND column_name = 'VERSION') THEN
        ALTER TABLE "HXDEFINITION_CANDIDATES" ADD COLUMN "VERSION" INTEGER NOT NULL DEFAULT 1;
        RAISE NOTICE '已为 HXDEFINITION_CANDIDATES 添加 VERSION 字段';
    ELSE
        RAISE NOTICE 'HXDEFINITION_CANDIDATES 的 VERSION 字段已存在';
    END IF;
END $$;

-- 为 HXNODE_CANDIDATES 添加 VERSION 字段
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'HXNODE_CANDIDATES' AND column_name = 'VERSION') THEN
        ALTER TABLE "HXNODE_CANDIDATES" ADD COLUMN "VERSION" INTEGER NOT NULL DEFAULT 1;
        RAISE NOTICE '已为 HXNODE_CANDIDATES 添加 VERSION 字段';
    ELSE
        RAISE NOTICE 'HXNODE_CANDIDATES 的 VERSION 字段已存在';
    END IF;
END $$;

-- 为 HXWKNODES 添加 VERSION 字段
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'HXWKNODES' AND column_name = 'VERSION') THEN
        ALTER TABLE "HXWKNODES" ADD COLUMN "VERSION" INTEGER NOT NULL DEFAULT 1;
        RAISE NOTICE '已为 HXWKNODES 添加 VERSION 字段';
    ELSE
        RAISE NOTICE 'HXWKNODES 的 VERSION 字段已存在';
    END IF;
END $$;

-- 为 HXWKINSTANCES 添加 VERSION 字段
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'HXWKINSTANCES' AND column_name = 'VERSION') THEN
        ALTER TABLE "HXWKINSTANCES" ADD COLUMN "VERSION" INTEGER NOT NULL DEFAULT 1;
        RAISE NOTICE '已为 HXWKINSTANCES 添加 VERSION 字段';
    ELSE
        RAISE NOTICE 'HXWKINSTANCES 的 VERSION 字段已存在';
    END IF;
END $$;

-- 为 HX_NODES_APPLICATION_FORMS 添加 VERSION 字段
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'HX_NODES_APPLICATION_FORMS' AND column_name = 'VERSION') THEN
        ALTER TABLE "HX_NODES_APPLICATION_FORMS" ADD COLUMN "VERSION" INTEGER NOT NULL DEFAULT 1;
        RAISE NOTICE '已为 HX_NODES_APPLICATION_FORMS 添加 VERSION 字段';
    ELSE
        RAISE NOTICE 'HX_NODES_APPLICATION_FORMS 的 VERSION 字段已存在';
    END IF;
END $$;

-- 更新现有数据的 VERSION 字段
UPDATE "HXWKDEFINITIONS" SET "VERSION" = 1 WHERE "VERSION" IS NULL OR "VERSION" = 0;
UPDATE "HXDEFINITION_CANDIDATES" SET "VERSION" = 1 WHERE "VERSION" IS NULL OR "VERSION" = 0;
UPDATE "HXNODE_CANDIDATES" SET "VERSION" = 1 WHERE "VERSION" IS NULL OR "VERSION" = 0;
UPDATE "HXWKNODES" SET "VERSION" = 1 WHERE "VERSION" IS NULL OR "VERSION" = 0;
UPDATE "HXWKINSTANCES" SET "VERSION" = 1 WHERE "VERSION" IS NULL OR "VERSION" = 0;
UPDATE "HX_NODES_APPLICATION_FORMS" SET "VERSION" = 1 WHERE "VERSION" IS NULL OR "VERSION" = 0;

-- 完成提示
DO $$
BEGIN
    RAISE NOTICE 'VERSION 字段添加和更新完成';
END $$; 