// <auto-generated />
using System;
using Hx.Workflow.EntityFrameworkCore.DbMigrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace Migrations
{
    [DbContext(typeof(WkDbMigrationsContext))]
    [Migration("20231103085825_init11")]
    partial class init11
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.MySql)
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Hx.Workflow.Domain.ApplicationForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<int>("ApplicationType")
                        .HasPrecision(1)
                        .HasColumnType("int")
                        .HasColumnName("APPLICATIONTYPE");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CODE");

                    b.Property<string>("DispalyName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DISPALYNAME");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NAME");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("PARENTID");

                    b.Property<Guid?>("WkNodeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("WKNODEID");

                    b.HasKey("Id");

                    b.HasIndex("WkNodeId");

                    b.ToTable("HXAPPLICATIONFORMS", null, t =>
                        {
                            t.HasComment("流程表单");
                        });
                });

            modelBuilder.Entity("Hx.Workflow.Domain.Persistence.WkDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID")
                        .HasComment("主键");

                    b.Property<string>("Color")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("COLOR")
                        .HasComment("显示颜色");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("Discription")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("DISCRIPTION")
                        .HasComment("定义描述");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ExtraProperties");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("char(36)")
                        .HasColumnName("GROUPID")
                        .HasComment("属于组");

                    b.Property<string>("Icon")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("ICON")
                        .HasComment("图标路径");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("char(36)")
                        .HasColumnName("LastModifierId");

                    b.Property<int?>("LimitTime")
                        .HasColumnType("int")
                        .HasColumnName("LIMITTIME")
                        .HasComment("限制时间");

                    b.Property<int>("SortNumber")
                        .HasColumnType("int")
                        .HasColumnName("SORTNUMBER")
                        .HasComment("排序");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("TENANTID")
                        .HasComment("租户Id");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TITLE")
                        .HasComment("标题");

                    b.Property<int>("Version")
                        .HasPrecision(9)
                        .HasColumnType("int")
                        .HasColumnName("VERSION")
                        .HasComment("版本号");

                    b.Property<int>("WkDefinitionState")
                        .HasPrecision(1)
                        .HasColumnType("int")
                        .HasColumnName("WKDEFINITIONSTATE")
                        .HasComment("是否开启");

                    b.HasKey("Id")
                        .HasName("Pk_WkDefinition");

                    b.ToTable("HXWKDEFINITIONS", null, t =>
                        {
                            t.HasComment("工作流定义");
                        });
                });

            modelBuilder.Entity("Hx.Workflow.Domain.Persistence.WkEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Data")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("EVENTDATA");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ISPROCESSED");

                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("EVENTKEY");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EVENTNAME");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("TENANTID");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime")
                        .HasColumnName("EVENTTIME");

                    b.HasKey("Id");

                    b.ToTable("HXWKEVENTS", null, t =>
                        {
                            t.HasComment("流程事件");
                        });
                });

            modelBuilder.Entity("Hx.Workflow.Domain.Persistence.WkExecutionError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("ErrorTime")
                        .HasColumnType("datetime")
                        .HasColumnName("ERRORTIME");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("MESSAGE");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("TENANTID");

                    b.Property<Guid>("WkExecutionPointerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("WKEXECUTIONPOINTERID");

                    b.Property<Guid>("WkInstanceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("WKINSTANCEID");

                    b.HasKey("Id");

                    b.ToTable("HXWKEXECUTIONERRORS", null, t =>
                        {
                            t.HasComment("执行错误");
                        });
                });

            modelBuilder.Entity("Hx.Workflow.Domain.Persistence.WkExecutionPointer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<string>("Children")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("CHILDREN");

                    b.Property<string>("ContextItem")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("CONTEXTITEM");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletionTime");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("ENDTIME");

                    b.Property<string>("EventData")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("EVENTDATA");

                    b.Property<string>("EventKey")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("EVENTKEY");

                    b.Property<string>("EventName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EVENTNAME");

                    b.Property<bool>("EventPublished")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("EVENTPUBLISHED");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("char(36)")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("Outcome")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("OUTCOME");

                    b.Property<string>("PersistenceData")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("PERSISTENCEDATA");

                    b.Property<string>("PredecessorId")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("PREDECESSORID");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int")
                        .HasColumnName("RETRYCOUNT");

                    b.Property<string>("Scope")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("SCOPE");

                    b.Property<DateTime?>("SleepUntil")
                        .HasColumnType("datetime")
                        .HasColumnName("SLEEPUNTIL");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("STARTTIME");

                    b.Property<int>("Status")
                        .HasPrecision(2)
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.Property<int>("StepId")
                        .HasColumnType("int")
                        .HasColumnName("STEPID");

                    b.Property<string>("StepName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("STEPNAME");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("TENANTID");

                    b.Property<Guid>("WkInstanceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("WKINSTANCEID");

                    b.HasKey("Id");

                    b.HasIndex("WkInstanceId");

                    b.ToTable("HXWKEXECUTIONPOINTER", null, t =>
                        {
                            t.HasComment("执行节点实例");
                        });
                });

            modelBuilder.Entity("Hx.Workflow.Domain.Persistence.WkExtensionAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<string>("AttributeKey")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ATTRIBUTEKEY");

                    b.Property<string>("AttributeValue")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("ATTRIBUTEVALUE");

                    b.Property<Guid>("ExecutionPointerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("EXECUTIONPOINTERID");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("TENANTID");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionPointerId");

                    b.ToTable("HXWKEXTENSIONATTRIBUTES", null, t =>
                        {
                            t.HasComment("执行节点属性");
                        });
                });

            modelBuilder.Entity("Hx.Workflow.Domain.Persistence.WkInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("CompleteTime")
                        .HasColumnType("datetime")
                        .HasColumnName("COMPLETETIME");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATETIME");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("CreatorId");

                    b.Property<string>("Data")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("DATA");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ExtraProperties");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("char(36)")
                        .HasColumnName("LastModifierId");

                    b.Property<long?>("NextExecution")
                        .HasColumnType("bigint")
                        .HasColumnName("NEXTEXECUTION");

                    b.Property<string>("Reference")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("REFERENCE");

                    b.Property<int>("Status")
                        .HasPrecision(1)
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("TENANTID");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("VERSION");

                    b.Property<Guid>("WkDifinitionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("WKDIFINITIONID");

                    b.HasKey("Id");

                    b.HasIndex("WkDifinitionId");

                    b.ToTable("HXWKINSTANCES", null, t =>
                        {
                            t.HasComment("流程实例");
                        });
                });

            modelBuilder.Entity("Hx.Workflow.Domain.Persistence.WkSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<string>("EventKey")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("EVENTKEY");

                    b.Property<string>("EventName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EVENTNAME");

                    b.Property<Guid>("ExecutionPointerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("EXECUTIONPOINTERID");

                    b.Property<string>("ExternalToken")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("EXTERNALTOKEN");

                    b.Property<DateTime?>("ExternalTokenExpiry")
                        .HasColumnType("datetime")
                        .HasColumnName("EXTERNALTOKENEXPIRY");

                    b.Property<string>("ExternalWorkerId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("EXTERNALWORKERID");

                    b.Property<int>("StepId")
                        .HasColumnType("int")
                        .HasColumnName("STEPID");

                    b.Property<DateTime>("SubscribeAsOf")
                        .HasColumnType("datetime")
                        .HasColumnName("SUBSCRIBEASOF");

                    b.Property<string>("SubscriptionData")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("SUBSCRIPTIONDATA");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("TENANTID");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("char(36)")
                        .HasColumnName("WORKFLOWID");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionPointerId");

                    b.ToTable("HXWKSUBSCRIPTIONS", null, t =>
                        {
                            t.HasComment("发布");
                        });
                });

            modelBuilder.Entity("Hx.Workflow.Domain.StepBodys.WkAuditor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("AuditTime")
                        .HasColumnType("datetime")
                        .HasColumnName("AUDITTIME");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ExecutionPointerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("EXECUTIONPOINTERID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Remark")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("REMARK");

                    b.Property<int>("Status")
                        .HasPrecision(1)
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("TENANTID");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("USERID");

                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("USERNAME");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("char(36)")
                        .HasColumnName("WORKFLOWID");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionPointerId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("HXWKAUDITORS", (string)null);
                });

            modelBuilder.Entity("Hx.Workflow.Domain.WkCandidate", b =>
                {
                    b.Property<Guid>("NodeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("NODEID");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("char(36)")
                        .HasColumnName("CANDIDATEID");

                    b.Property<bool>("DefaultSelection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("DEFAULTSELECTION");

                    b.Property<string>("DisplayUserName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DISPLAYUSERNAME");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("USERNAME");

                    b.HasKey("NodeId", "CandidateId");

                    b.HasIndex("CandidateId");

                    b.ToTable("HXWKCANDIDATES", (string)null);
                });

            modelBuilder.Entity("Hx.Workflow.Domain.WkConNodeCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Field")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("FIELD");

                    b.Property<string>("Operator")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("OPERATOR");

                    b.Property<string>("Value")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("VALUE");

                    b.Property<Guid>("WkConditionNodeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("WKCONDITIONNODEID");

                    b.HasKey("Id");

                    b.HasIndex("WkConditionNodeId");

                    b.ToTable("HXWKCONNODECONDITIONS", null, t =>
                        {
                            t.HasComment("条件集合");
                        });
                });

            modelBuilder.Entity("Hx.Workflow.Domain.WkConditionNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("LABEL");

                    b.Property<string>("NextNodeName")
                        .HasColumnType("longtext")
                        .HasColumnName("NEXTNODENAME");

                    b.Property<Guid>("WkNodeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("WKNODEID");

                    b.HasKey("Id");

                    b.HasIndex("WkNodeId");

                    b.ToTable("HXWKCONDITIONNODES", null, t =>
                        {
                            t.HasComment("节点条件");
                        });
                });

            modelBuilder.Entity("Hx.Workflow.Domain.WkNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DISPLAYNAME");

                    b.Property<int?>("LimitTime")
                        .HasColumnType("int")
                        .HasColumnName("LIMITTIME");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NAME");

                    b.Property<int>("NodeFormType")
                        .HasPrecision(1)
                        .HasColumnType("int")
                        .HasColumnName("NODEFORMTYPE");

                    b.Property<int>("StepNodeType")
                        .HasPrecision(1)
                        .HasColumnType("int")
                        .HasColumnName("STEPNODETYPE");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("VERSION");

                    b.Property<Guid?>("WkDefinitionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("WKDIFINITIONID");

                    b.Property<Guid?>("WkStepBodyId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WkDefinitionId");

                    b.HasIndex("WkStepBodyId");

                    b.ToTable("HXWKNODES", null, t =>
                        {
                            t.HasComment("执行节点");
                        });
                });

            modelBuilder.Entity("Hx.Workflow.Domain.WkNodePara", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("KEY");

                    b.Property<string>("Value")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("VALUE");

                    b.Property<Guid>("WkNodeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("WKNODEID");

                    b.HasKey("Id");

                    b.HasIndex("WkNodeId");

                    b.ToTable("HXWKNODEPARAS", null, t =>
                        {
                            t.HasComment("步骤参数");
                        });
                });

            modelBuilder.Entity("Hx.Workflow.Domain.WkPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<int>("Bottom")
                        .HasColumnType("int")
                        .HasColumnName("BOTTOM");

                    b.Property<int>("Left")
                        .HasColumnType("int")
                        .HasColumnName("LEFT");

                    b.Property<int>("Right")
                        .HasColumnType("int")
                        .HasColumnName("RIGHT");

                    b.Property<int>("Top")
                        .HasColumnType("int")
                        .HasColumnName("TOP");

                    b.Property<Guid>("WkNodeId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WkNodeId");

                    b.ToTable("HXWKPOINTS", (string)null);
                });

            modelBuilder.Entity("Hx.Workflow.Domain.WkStepBody", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AssemblyFullName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ASSEMBLYFULLNAME");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DISPLAYNAME");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("char(36)")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("TypeFullName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("TYPEFULLNAME");

                    b.HasKey("Id");

                    b.ToTable("HXWKSTEPBODYS", null, t =>
                        {
                            t.HasComment("节点实体");
                        });
                });

            modelBuilder.Entity("Hx.Workflow.Domain.WkStepBodyParam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DISPLAYNAME");

                    b.Property<string>("Key")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("KEY");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NAME");

                    b.Property<int>("StepBodyParaType")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("VALUE");

                    b.Property<Guid>("WkNodeId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WkNodeId");

                    b.ToTable("HXWKSTEPBODYPARAMS", null, t =>
                        {
                            t.HasComment("节点参数");
                        });
                });

            modelBuilder.Entity("Hx.Workflow.Domain.ApplicationForm", b =>
                {
                    b.HasOne("Hx.Workflow.Domain.WkNode", "WkNode")
                        .WithMany("ApplicationForms")
                        .HasForeignKey("WkNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("Pk_WkNode_App");

                    b.Navigation("WkNode");
                });

            modelBuilder.Entity("Hx.Workflow.Domain.Persistence.WkExecutionPointer", b =>
                {
                    b.HasOne("Hx.Workflow.Domain.Persistence.WkInstance", "WkInstance")
                        .WithMany("ExecutionPointers")
                        .HasForeignKey("WkInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Pk_Instance_Pointer");

                    b.Navigation("WkInstance");
                });

            modelBuilder.Entity("Hx.Workflow.Domain.Persistence.WkExtensionAttribute", b =>
                {
                    b.HasOne("Hx.Workflow.Domain.Persistence.WkExecutionPointer", "WkExecutionPointer")
                        .WithMany("ExtensionAttributes")
                        .HasForeignKey("ExecutionPointerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Pk_Pointer_Attribute");

                    b.Navigation("WkExecutionPointer");
                });

            modelBuilder.Entity("Hx.Workflow.Domain.Persistence.WkInstance", b =>
                {
                    b.HasOne("Hx.Workflow.Domain.Persistence.WkDefinition", "WkDefinition")
                        .WithMany()
                        .HasForeignKey("WkDifinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Pk_Instance_Definition");

                    b.Navigation("WkDefinition");
                });

            modelBuilder.Entity("Hx.Workflow.Domain.Persistence.WkSubscription", b =>
                {
                    b.HasOne("Hx.Workflow.Domain.Persistence.WkExecutionPointer", null)
                        .WithMany("WkSubscriptions")
                        .HasForeignKey("ExecutionPointerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Pk_Pointer_Subscript");
                });

            modelBuilder.Entity("Hx.Workflow.Domain.StepBodys.WkAuditor", b =>
                {
                    b.HasOne("Hx.Workflow.Domain.Persistence.WkExecutionPointer", "ExecutionPointer")
                        .WithMany()
                        .HasForeignKey("ExecutionPointerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Pk_WkAuditor_ExecPointer");

                    b.HasOne("Hx.Workflow.Domain.Persistence.WkInstance", "Workflow")
                        .WithMany("WkAuditors")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Pk_WkAuditor_WkInstance");

                    b.Navigation("ExecutionPointer");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Hx.Workflow.Domain.WkCandidate", b =>
                {
                    b.HasOne("Hx.Workflow.Domain.Persistence.WkExecutionPointer", null)
                        .WithMany("WkCandidates")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Pk_Pointer_Candidate");

                    b.HasOne("Hx.Workflow.Domain.Persistence.WkDefinition", null)
                        .WithMany("WkCandidates")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Pk_WkDef_Candidate");

                    b.HasOne("Hx.Workflow.Domain.WkNode", null)
                        .WithMany("WkCandidates")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Pk_WkNode_Candidate");
                });

            modelBuilder.Entity("Hx.Workflow.Domain.WkConNodeCondition", b =>
                {
                    b.HasOne("Hx.Workflow.Domain.WkConditionNode", null)
                        .WithMany("WkConNodeConditions")
                        .HasForeignKey("WkConditionNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Pk_Candition_ConCondition");
                });

            modelBuilder.Entity("Hx.Workflow.Domain.WkConditionNode", b =>
                {
                    b.HasOne("Hx.Workflow.Domain.WkNode", null)
                        .WithMany("NextNodes")
                        .HasForeignKey("WkNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Pk_WkNode_Candition");
                });

            modelBuilder.Entity("Hx.Workflow.Domain.WkNode", b =>
                {
                    b.HasOne("Hx.Workflow.Domain.Persistence.WkDefinition", "WkDefinition")
                        .WithMany("Nodes")
                        .HasForeignKey("WkDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("Pk_WkDef_WkNode");

                    b.HasOne("Hx.Workflow.Domain.WkStepBody", "StepBody")
                        .WithMany()
                        .HasForeignKey("WkStepBodyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("Pk_WkNode_WkStepBody");

                    b.Navigation("StepBody");

                    b.Navigation("WkDefinition");
                });

            modelBuilder.Entity("Hx.Workflow.Domain.WkNodePara", b =>
                {
                    b.HasOne("Hx.Workflow.Domain.WkNode", null)
                        .WithMany("OutcomeSteps")
                        .HasForeignKey("WkNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Pk_WkNode_OutcomeSteps");
                });

            modelBuilder.Entity("Hx.Workflow.Domain.WkPoint", b =>
                {
                    b.HasOne("Hx.Workflow.Domain.WkNode", null)
                        .WithMany("Position")
                        .HasForeignKey("WkNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Pk_WkNode_WkPoint");
                });

            modelBuilder.Entity("Hx.Workflow.Domain.WkStepBodyParam", b =>
                {
                    b.HasOne("Hx.Workflow.Domain.WkStepBody", null)
                        .WithMany("Inputs")
                        .HasForeignKey("WkNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Pk_WkStepBody_WkParam");
                });

            modelBuilder.Entity("Hx.Workflow.Domain.Persistence.WkDefinition", b =>
                {
                    b.Navigation("Nodes");

                    b.Navigation("WkCandidates");
                });

            modelBuilder.Entity("Hx.Workflow.Domain.Persistence.WkExecutionPointer", b =>
                {
                    b.Navigation("ExtensionAttributes");

                    b.Navigation("WkCandidates");

                    b.Navigation("WkSubscriptions");
                });

            modelBuilder.Entity("Hx.Workflow.Domain.Persistence.WkInstance", b =>
                {
                    b.Navigation("ExecutionPointers");

                    b.Navigation("WkAuditors");
                });

            modelBuilder.Entity("Hx.Workflow.Domain.WkConditionNode", b =>
                {
                    b.Navigation("WkConNodeConditions");
                });

            modelBuilder.Entity("Hx.Workflow.Domain.WkNode", b =>
                {
                    b.Navigation("ApplicationForms");

                    b.Navigation("NextNodes");

                    b.Navigation("OutcomeSteps");

                    b.Navigation("Position");

                    b.Navigation("WkCandidates");
                });

            modelBuilder.Entity("Hx.Workflow.Domain.WkStepBody", b =>
                {
                    b.Navigation("Inputs");
                });
#pragma warning restore 612, 618
        }
    }
}
