name: NuGet Package Workflow

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.104'

    - name: Build and pack NuGet packages
      run: |
        dotnet build src/Hx.Workflow.Application/Hx.Workflow.Application.csproj -c Release
        dotnet pack src/Hx.Workflow.Application/Hx.Workflow.Application.csproj -c Release -o ./src/Hx.Workflow.Application/bin/Debug
        cp ./src/Hx.Workflow.Application/bin/Debug/Hx.Workflow.Application.1.0.1.nupkg $GITHUB_WORKSPACE
